firewall_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('firewall_logs/', views.firewall_logs, name='firewall_logs'),
    path('firewall_rules/', views.firewall_rules, name='firewall_rules'),
    path('delete_rule/<int:rule_id>/', views.delete_rule, name='delete_rule'),
    path('move_rule/<int:rule_id>/<direction>/', views.move_rule, name='move_rule'),
]

internet_firewall/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("firewall_app.urls")),
]

firewall_app/models.py
# models.py
from django.db import models
from django import forms


class FirewallRule(models.Model):
    priority = models.PositiveIntegerField(default=0)
    src_ip = models.GenericIPAddressField(default='0.0.0.0')  # Default is 'any'
    dest_ip = models.GenericIPAddressField(default='0.0.0.0')  # Default is 'any'
    src_port = models.IntegerField(default=-1)  # Default is 'any'
    dest_port = models.IntegerField(default=-1)  # Default is 'any'
    
    PROTOCOL_CHOICES = [
    ('tcp', 'Tcp'),
    ('udp', 'Udp'),
    ('any', 'Any'),
    ]

    ACTION_CHOICES = [
        ('allow', 'Allow'),
        ('deny', 'Deny'),
    ]
    action = models.CharField(max_length=5, choices=ACTION_CHOICES, default='deny')  # Default is 'allow'

    protocol = models.CharField(max_length=3, choices=PROTOCOL_CHOICES, default='any')  # Default is 'allow'

    def __str__(self):
        return f"{self.priority} - {self.src_ip} to {self.dest_ip} ({self.protocol}): {self.action}"


class FirewallLog(models.Model):
    src_ip = models.GenericIPAddressField()
    dest_ip = models.GenericIPAddressField()
    src_port = models.PositiveIntegerField()
    dest_port = models.PositiveIntegerField()
    bytes_sent = models.PositiveBigIntegerField(default=0)
    bytes_received = models.PositiveBigIntegerField(default=0)
    no_of_packets = models.PositiveIntegerField(default=0)
    protocol = models.CharField(max_length=10)
    detail=models.CharField(max_length=100)
    action = models.CharField(max_length=10)
    timestamp = models.DateTimeField(auto_now_add=True)

firewall_app/forms.py
# firewall_app/forms.py
from django import forms
from django.core.exceptions import ValidationError
import ipaddress

from .models import FirewallRule

class FirewallRuleForm(forms.ModelForm):
    class Meta:
        model = FirewallRule
        fields = ['src_ip', 'dest_ip', 'src_port', 'dest_port', 'protocol', 'action']

    def clean_src_ip(self):
        src_ip = self.cleaned_data['src_ip']

        if not is_valid_ip(src_ip):
            raise ValidationError("Invalid source IP address.")
        return src_ip

    def clean_dest_ip(self):
        dest_ip = self.cleaned_data['dest_ip']

        if not is_valid_ip(dest_ip):
            raise ValidationError("Invalid destination IP address.")
        return dest_ip

    def clean_src_port(self):
        src_port = self.cleaned_data['src_port']

        if not is_valid_port(src_port):
            raise ValidationError("Invalid source port.")
        return src_port

    def clean_dest_port(self):
        dest_port = self.cleaned_data['dest_port']

        if not is_valid_port(dest_port):
            raise ValidationError("Invalid destination port.")
        return dest_port


def is_valid_port(port_):
    return port_ > 0 or port_ == -1

def is_valid_ip(value):
    try:
        if(value == '*'):
            return True
        ipaddress.IPv4Address(value)
        return True
    except ipaddress.AddressValueError:
        return False

firewall_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.views.decorators.http import require_POST
from django.db.models import Max

from .forms import FirewallRuleForm
from .models import FirewallRule, FirewallLog

class HomePageView(TemplateView):
    template_name = 'firewall_app/index.html'


def firewall_logs(request):
    logs = FirewallLog.objects.all()
    return render(request, 'firewall_app/firewall_logs.html', {'logs': logs})

def firewall_rules(request):
    rules = FirewallRule.objects.order_by('priority') 
    max_priority = FirewallRule.objects.aggregate(Max('priority'))['priority__max']
    
    default_priority = max_priority + 1 if max_priority is not None else 0
    if request.method == 'POST':
        form = FirewallRuleForm(request.POST)
        if form.is_valid():
            form.instance.priority = default_priority
            form.save()
            return redirect('firewall_rules')  # Redirect to the same page after adding a rule
    else:
        form = FirewallRuleForm()

    return render(request, 'firewall_app/firewall_rules.html', {'rules': rules, 'form': form})

def delete_rule(request, rule_id):
    rule = get_object_or_404(FirewallRule, id=rule_id)
    rule.delete()
    return redirect('firewall_rules')  # Redirect to the firewall rules page after deleting a rule

def index(request):
    return HttpResponse("Hello, world. You're at the firewall-app index.")


@require_POST
def move_rule(request, rule_id, direction):
    rule = get_object_or_404(FirewallRule, id=rule_id)
    rules = list(FirewallRule.objects.order_by('priority'))
    print(rules)
    print(rule)
    current_order = rule.priority
    index = rules.index(rule)
   # (variable) rules: BaseManager[FirewallRule]

    if direction == 'up' and index > 0:
        # Swap priority with the rule above
        rule_above = rules[index - 1]
        rule.priority, rule_above.priority = rule_above.priority, current_order
        rule.save()
        rule_above.save()
    elif direction == 'down' and index < len(rules) - 1:
        # Swap order with the rule below
        rule_below = rules[index + 1]
        rule.priority, rule_below.priority = rule_below.priority, current_order
        rule.save()
        rule_below.save()

    return redirect('firewall_rules')

firewall_app/templates/firewall_app/firewall_logs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'firewall_app/styles.css' %}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-image: url('{% static "firewall_app/background.jpg" %}');
            background-size:cover;
            background-clip: border-box;
            background-attachment: fixed;
            width: 97vw;
            height: 100vh; 
        }
        h1, h5, p {
            text-align: left;
            padding: 2px;
            max-width: 500px;
            background-color: rgba(0, 0, 0, 0);
            color: #8a8ae3; /* Light purple text color */
        }
    </style>
    <title>Firewall Logs</title>
</head>
<body>
    <nav>
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'firewall_rules' %}">Firewall Rules</a>
    </nav>
    <h2>Firewall Logs</h2>
    <table id="firewall-logs-table">
        <!-- Table headers -->
        <thead>
            <tr>
                <th>Timestamp</th>
                <th>Source IP</th>
                <th>Destination IP</th>
                <th>Source Port</th>
                <th>Destination Port</th>
                <th>Protocol</th>
                <th>Bytes Sent (Session)</th>
                <th>Bytes Received (Session)</th>
                <th>Total Packets (Session)</th>
                <th>Action</th>  
                <th>Detail</th>
            </tr>
        </thead>
        <!-- Table body -->
        <tbody>
            {% for log in logs %}
                <tr>
                    <td>{{ log.timestamp }}</td>                   
                    <td>{{ log.src_ip }}</td>
                    <td>{{ log.dest_ip }}</td>
                    <td>{{ log.src_port }}</td>
                    <td>{{ log.dest_port }}</td>
                    <td>{{ log.protocol }}</td>
                    <td>{{log.bytes_sent}}</td>
                    <td>{{log.bytes_received}}</td>
                    <td>{{log.no_of_packets}}</td>
                    <td>{{ log.action }}</td>
                    <td>{{log.detail}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Include jQuery and DataTables script -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            // Use DataTables for table filtering
            $('#firewall-logs-table').DataTable();
        });
    </script>

</body>
</html>

firewall_app/templates/firewall_app/firewall_rules.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'firewall_app/styles.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-image: url('{% static "firewall_app/background.jpg" %}');
            background-size:cover;
            background-clip: border-box;
            background-attachment: fixed;
            width: 97vw;
            height: 100vh;
            overflow-x: hidden;
        }
        h1, h5, p {
            text-align: left;
            padding: 2px;
            max-width: 500px;
            background-color: rgba(0, 0, 0, 0);
            color: #8a8ae3; /* Light purple text color */
        }
    </style>
    <title>Firewall Rules</title>
</head>
<body>
    <nav>
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'firewall_logs' %}">Firewall Logs</a>
    </nav>
    <h1>Firewall Rules</h1>
        {% csrf_token %}
        <table>
            <thead>
                <tr>
                    <th>Source IP</th>
                    <th>Destination IP</th>
                    <th>Source Port</th>
                    <th>Destination Port</th>
                    <th>Protocol</th>
                    <th>Action</th>
                    <th>Move</th>
                    <th>Delete</th> 
                </tr>
            </thead>
            <tbody>
                {% for rule in rules %}
                    <tr>
                        <td>{{ rule.src_ip }}</td>
                        <td>{{ rule.dest_ip }}</td>
                        <td>{{ rule.src_port }}</td>
                        <td>{{ rule.dest_port }}</td>
                        <td>{{ rule.protocol }}</td>
                        <td>{{ rule.get_action_display }}</td>
                        <td>
                            <form method="post" action="{% url 'move_rule' rule.id 'up' %}">
                                {% csrf_token %}
                                <button type="submit">Move Up</button>
                            </form>
                            <form method="post" action="{% url 'move_rule' rule.id 'down' %}">
                                {% csrf_token %}
                                <button type="submit">Move Down</button>
                            </form>
                        </td>
                        <td>
                            <form method="post" action="{% url 'delete_rule' rule.id %}">
                                {% csrf_token %}
                                <button type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <h1>Add New Rule</h1>
        <form method="post" action="">
            {% csrf_token %}
            <table>
                <thead>
                    <tr>
                        <th>Source IP</th>
                        <th>Destination IP</th>
                        <th>Source Port</th>
                        <th>Destination Port</th>
                        <th>Protocol</th>
                        <th>Action</th>
                        <th>Submit</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            {{ form.src_ip }}
                            {{ form.src_ip.errors }}
                        </td>
                        <td>
                            {{ form.dest_ip }}
                            {{ form.dest_ip.errors }}
                        </td>
                        <td>
                            {{ form.src_port }}
                            {{ form.src_port.errors }}
                        </td>
                        <td>
                            {{ form.dest_port }}
                            {{ form.dest_port.errors }}
                        </td>
                        <td>
                            {{ form.protocol }}
                        </td>
                        <td>
                            {{ form.action }}
                        </td>
                        <td>
                            <button type="submit">Add Rule</button>
                        </td>
                    </tr>
                </tbody>
            </table>
            <h5>Enter 0.0.0.0 to specify all IP Addresses and -1 to specify all Ports</h5>
        </form>
    <br>
</body>
</html>

firewall_app/templates/firewall_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'firewall_app/styles.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-image: url('{% static "firewall_app/background.jpg" %}');
            background-size:cover;
            background-clip: border-box;
            background-attachment: fixed;
            width: 100vw;
            height: 100vh; 
            overflow-y: hidden; /* Hide vertical scrollbar */
            overflow-x: hidden;
        }
        h1, h5, p {
            text-align: left;
            padding: 2px;
            max-width: 500px;
            background-color: rgba(0, 0, 0, 0);
            color: #8a8ae3; /* Light purple text color */
        }
    </style>
    <title>Home</title>
</head>
<body>

<nav>
    <a href="{% url 'firewall_rules' %}">Firewall Rules</a>
    <a href="{% url 'firewall_logs' %}">Firewall Logs</a>
</nav>

<h1>Welcome to the Firewall Protected App</h1>
<p>A 2-layered firewall to protect your application</p>

</body>
</html>